import json
from pathlib import Path

sem = {
  'nodes': [
    {'id': 'sas', 'label': 'SAS (Snoopy Agent Smart)', 'file_type': 'concept', 'source_file': 'README.md'},
    {'id': 'sc', 'label': 'SC (SnoopyClaw 主脑)', 'file_type': 'concept', 'source_file': 'README.md'},
    {'id': 'slow-is-fast', 'label': '慢即是快', 'file_type': 'concept', 'source_file': '04-工作准则/Snoopy Agent Smart (SAS)工作准则-v1.5.md'},
    {'id': 'ceo-mode', 'label': 'CEO 模式协作架构', 'file_type': 'concept', 'source_file': '04-工作准则/Snoopy Agent Smart (SAS)工作准则-v1.5.md'},
    {'id': 'six-phase', 'label': '六阶段工作流程', 'file_type': 'concept', 'source_file': 'README.md'},
    {'id': 'l0-user', 'label': 'L0 用户 (CEO)', 'file_type': 'concept', 'source_file': '04-工作准则/Snoopy Agent Smart (SAS)工作准则-v1.5.md'},
    {'id': 'l1-sc', 'label': 'L1 SC 主脑', 'file_type': 'concept', 'source_file': '04-工作准则/Snoopy Agent Smart (SAS)工作准则-v1.5.md'},
    {'id': 'l2-leader', 'label': 'L2 Leader Agent', 'file_type': 'concept', 'source_file': '04-工作准则/Snoopy Agent Smart (SAS)工作准则-v1.5.md'},
    {'id': 'l3-worker', 'label': 'L3 Worker Agent', 'file_type': 'concept', 'source_file': '04-工作准则/Snoopy Agent Smart (SAS)工作准则-v1.5.md'},
    {'id': 'complexity-l1', 'label': 'L1 简单任务', 'file_type': 'concept', 'source_file': '04-工作准则/Snoopy Agent Smart (SAS)工作准则-v1.5.md'},
    {'id': 'complexity-l2', 'label': 'L2 中等任务', 'file_type': 'concept', 'source_file': '04-工作准则/Snoopy Agent Smart (SAS)工作准则-v1.5.md'},
    {'id': 'complexity-l3', 'label': 'L3 复杂任务', 'file_type': 'concept', 'source_file': '04-工作准则/Snoopy Agent Smart (SAS)工作准则-v1.5.md'},
    {'id': 'permission-l0', 'label': 'L0 权限', 'file_type': 'concept', 'source_file': '04-工作准则/Snoopy Agent Smart (SAS)工作准则-v1.5.md'},
    {'id': 'permission-l1', 'label': 'L1 权限', 'file_type': 'concept', 'source_file': '04-工作准则/Snoopy Agent Smart (SAS)工作准则-v1.5.md'},
    {'id': 'permission-l2', 'label': 'L2 权限', 'file_type': 'concept', 'source_file': '04-工作准则/Snoopy Agent Smart (SAS)工作准则-v1.5.md'},
    {'id': 'permission-l3', 'label': 'L3 权限', 'file_type': 'concept', 'source_file': '04-工作准则/Snoopy Agent Smart (SAS)工作准则-v1.5.md'},
    {'id': 'agent-main', 'label': 'main (SC)', 'file_type': 'agent', 'source_file': 'README.md'},
    {'id': 'agent-sas-leader', 'label': 'sas-leader', 'file_type': 'agent', 'source_file': 'README.md'},
    {'id': 'agent-sas-default', 'label': 'sas-default', 'file_type': 'agent', 'source_file': 'README.md'},
    {'id': 'agent-sas-sop-expert', 'label': 'sas-sop-expert', 'file_type': 'agent', 'source_file': 'README.md'},
    {'id': 'agent-xiaowen', 'label': 'xiaowen', 'file_type': 'agent', 'source_file': 'README.md'},
    {'id': 'agent-hr', 'label': 'hr', 'file_type': 'agent', 'source_file': 'README.md'},
    {'id': 'agent-tech-news', 'label': 'tech-news', 'file_type': 'agent', 'source_file': 'README.md'},
    {'id': 'agent-doc-expert', 'label': 'doc-expert', 'file_type': 'agent', 'source_file': 'README.md'},
    {'id': 'agent-weather', 'label': 'weather', 'file_type': 'agent', 'source_file': 'README.md'},
    {'id': 'model-m27-highspeed', 'label': 'MiniMax-M2.7-highspeed', 'file_type': 'model', 'source_file': '大模型信息与Agent分配依据.md'},
    {'id': 'model-m27', 'label': 'MiniMax-M2.7', 'file_type': 'model', 'source_file': '大模型信息与Agent分配依据.md'},
    {'id': 'model-glm-5-turbo', 'label': 'GLM-5-Turbo', 'file_type': 'model', 'source_file': '大模型信息与Agent分配依据.md'},
    {'id': 'model-deepseek-chat', 'label': 'DeepSeek Chat', 'file_type': 'model', 'source_file': '大模型信息与Agent分配依据.md'},
    {'id': 'model-glm-45-air', 'label': 'GLM-4.5-Air', 'file_type': 'model', 'source_file': '大模型信息与Agent分配依据.md'},
    {'id': 'model-glm-47', 'label': 'GLM-4.7', 'file_type': 'model', 'source_file': '大模型信息与Agent分配依据.md'},
    {'id': 'provider-minimax', 'label': 'MiniMax Provider', 'file_type': 'concept', 'source_file': '大模型信息与Agent分配依据.md'},
    {'id': 'provider-zhipu', 'label': '智谱 GLM Provider', 'file_type': 'concept', 'source_file': '大模型信息与Agent分配依据.md'},
    {'id': 'provider-deepseek', 'label': 'DeepSeek Provider', 'file_type': 'concept', 'source_file': '大模型信息与Agent分配依据.md'},
    {'id': 'provider-siliconflow', 'label': '硅基流动 SiliconFlow', 'file_type': 'concept', 'source_file': '大模型信息与Agent分配依据.md'},
    {'id': 'tool-openclaw', 'label': 'OpenClaw 平台', 'file_type': 'tool', 'source_file': '04-工作准则/Snoopy Agent Smart (SAS)工作准则-v1.5.md'},
    {'id': 'tool-coze', 'label': '扣子 Coze', 'file_type': 'tool', 'source_file': '04-工作准则/Snoopy Agent Smart (SAS)工作准则-v1.5.md'},
    {'id': 'tool-n8n', 'label': 'n8n', 'file_type': 'tool', 'source_file': '04-工作准则/Snoopy Agent Smart (SAS)工作准则-v1.5.md'},
    {'id': 'tool-github', 'label': 'GitHub', 'file_type': 'tool', 'source_file': 'README.md'},
    {'id': 'tool-feishu', 'label': '飞书', 'file_type': 'tool', 'source_file': '04-工作准则/Snoopy Agent Smart (SAS)工作准则-v1.5.md'},
    {'id': 'tool-task-decompose', 'label': 'task_decompose.py', 'file_type': 'tool', 'source_file': '05-构建与验证/SAS-V1.5-构建实录.md'},
    {'id': 'tool-task-logger', 'label': 'task_logger.py', 'file_type': 'tool', 'source_file': '05-构建与验证/SAS-V1.5-构建实录.md'},
    {'id': 'tool-memory-lancedb', 'label': 'memory-lancedb-pro', 'file_type': 'tool', 'source_file': '05-构建与验证/SAS-V1.5-构建实录.md'},
    {'id': 'tool-lossless-claw', 'label': 'lossless-claw-enhanced', 'file_type': 'tool', 'source_file': '05-构建与验证/SAS-V1.5-构建实录.md'},
    {'id': 'tool-openclaw-lark', 'label': 'openclaw-lark', 'file_type': 'tool', 'source_file': '05-构建与验证/SAS-V1.5-构建实录.md'},
    {'id': 'harness-leader', 'label': 'harness-leader 技能', 'file_type': 'tool', 'source_file': '02-可行性分析/Snoopy Agent Smart (SAS) 可行性分析报告.md'},
    {'id': 'phase-1', 'label': '阶段1: 接收任务', 'file_type': 'phase', 'source_file': 'README.md'},
    {'id': 'phase-2', 'label': '阶段2: 制定计划', 'file_type': 'phase', 'source_file': 'README.md'},
    {'id': 'phase-3', 'label': '阶段3: 执行工作', 'file_type': 'phase', 'source_file': 'README.md'},
    {'id': 'phase-4', 'label': '阶段4: 质量检查', 'file_type': 'phase', 'source_file': 'README.md'},
    {'id': 'phase-5', 'label': '阶段5: 交付成果', 'file_type': 'phase', 'source_file': 'README.md'},
    {'id': 'phase-6', 'label': '阶段6: 复盘归档', 'file_type': 'phase', 'source_file': 'README.md'},
    {'id': 'repo-sas', 'label': 'SAS 仓库', 'file_type': 'concept', 'source_file': 'README.md'},
    {'id': 'repo-sas-script', 'label': 'SAS-script 仓库', 'file_type': 'concept', 'source_file': 'README.md'},
    {'id': 'sas-v1-0', 'label': 'SAS v1.0', 'file_type': 'version', 'source_file': 'README.md'},
    {'id': 'sas-v1-1', 'label': 'SAS v1.1', 'file_type': 'version', 'source_file': 'README.md'},
    {'id': 'sas-v1-2', 'label': 'SAS v1.2', 'file_type': 'version', 'source_file': 'README.md'},
    {'id': 'sas-v1-3', 'label': 'SAS v1.3', 'file_type': 'version', 'source_file': 'README.md'},
    {'id': 'sas-v1-4', 'label': 'SAS v1.4', 'file_type': 'version', 'source_file': 'README.md'},
    {'id': 'sas-v1-5', 'label': 'SAS v1.5', 'file_type': 'version', 'source_file': 'README.md'},
    {'id': 'sas-v1-6', 'label': 'SAS v1.6', 'file_type': 'version', 'source_file': 'README.md'},
    {'id': 'case-library', 'label': '案例库', 'file_type': 'concept', 'source_file': '04-工作准则/Snoopy Agent Smart (SAS)工作准则-v1.5.md'},
    {'id': 'agent-capability-profile', 'label': 'Agent 能力档案', 'file_type': 'concept', 'source_file': '04-工作准则/Snoopy Agent Smart (SAS)工作准则-v1.5.md'},
    {'id': 'task-report-card', 'label': '任务级成绩单', 'file_type': 'concept', 'source_file': '04-工作准则/Snoopy Agent Smart (SAS)工作准则-v1.5.md'},
    {'id': 'sas-efficiency', 'label': 'SAS体系效能衡量指标', 'file_type': 'concept', 'source_file': '04-工作准则/Snoopy Agent Smart (SAS)工作准则-v1.5.md'},
    {'id': 'risk-prediction', 'label': '任务风险预测机制', 'file_type': 'concept', 'source_file': '04-工作准则/Snoopy Agent Smart (SAS)工作准则-v1.5.md'},
    {'id': 'user-feedback-loop', 'label': '用户反馈闭环', 'file_type': 'concept', 'source_file': '04-工作准则/Snoopy Agent Smart (SAS)工作准则-v1.5.md'},
    {'id': 'task-urgency', 'label': '任务紧急度分级', 'file_type': 'concept', 'source_file': '04-工作准则/Snoopy Agent Smart (SAS)工作准则-v1.5.md'},
    {'id': 'failure-archive', 'label': '失败案例专项归档', 'file_type': 'concept', 'source_file': '04-工作准则/Snoopy Agent Smart (SAS)工作准则-v1.5.md'},
    {'id': 'auto-approval', 'label': '自动审批规则', 'file_type': 'concept', 'source_file': '04-工作准则/Snoopy Agent Smart (SAS)工作准则-v1.5.md'},
    {'id': 'skill-vetter', 'label': 'skill-vetter 安全审计', 'file_type': 'concept', 'source_file': '04-工作准则/Snoopy Agent Smart (SAS)工作准则-v1.5.md'},
    {'id': 'watchdog', 'label': '看门狗机制', 'file_type': 'concept', 'source_file': '04-工作准则/Snoopy Agent Smart (SAS)工作准则-v1.5.md'},
    {'id': 'idle-detection', 'label': '空转检测', 'file_type': 'concept', 'source_file': '04-工作准则/Snoopy Agent Smart (SAS)工作准则-v1.5.md'},
    {'id': 'session-reset', 'label': '会话重置恢复', 'file_type': 'concept', 'source_file': '04-工作准则/Snoopy Agent Smart (SAS)工作准则-v1.5.md'},
    {'id': 'token-monitor', 'label': 'Token 监控', 'file_type': 'concept', 'source_file': '04-工作准则/Snoopy Agent Smart (SAS)工作准则-v1.5.md'},
    {'id': 'three-layer-arch', 'label': '三层架构', 'file_type': 'concept', 'source_file': '05-构建与验证/SAS-V1.5-构建实录.md'},
    {'id': 'sas-engine-plugin', 'label': 'sas-engine 插件', 'file_type': 'tool', 'source_file': '05-构建与验证/SAS-V1.5-构建实录.md'},
    {'id': 'model-router', 'label': '模型路由策略', 'file_type': 'concept', 'source_file': '大模型信息与Agent分配依据.md'},
    {'id': 'harness-framework', 'label': 'Anthropic Effective Harnesses', 'file_type': 'concept', 'source_file': '02-可行性分析/Snoopy Agent Smart (SAS) 可行性分析报告.md'},
    {'id': 'four-iron-rules', 'label': '四条执行铁律', 'file_type': 'concept', 'source_file': '04-工作准则/Snoopy Agent Smart (SAS)工作准则-v1.5.md'},
    {'id': 'daily-checklist', 'label': '主脑每日工作检查清单', 'file_type': 'concept', 'source_file': '04-工作准则/Snoopy Agent Smart (SAS)工作准则-v1.5.md'},
    {'id': 'iteration-cycle', 'label': '准则迭代周期', 'file_type': 'concept', 'source_file': '04-工作准则/Snoopy Agent Smart (SAS)工作准则-v1.5.md'},
    {'id': 'sop-expert-workflow', 'label': 'SOP专家每日优化', 'file_type': 'concept', 'source_file': '04-工作准则/Snoopy Agent Smart (SAS)工作准则-v1.5.md'},
    {'id': 'systematic-thinking', 'label': '系统化思维', 'file_type': 'concept', 'source_file': '04-工作准则/Snoopy Agent Smart (SAS)工作准则-v1.5.md'},
    {'id': 'feasibility-report', 'label': '可行性分析报告', 'file_type': 'document', 'source_file': '02-可行性分析/Snoopy Agent Smart (SAS) 可行性分析报告.md'},
    {'id': 'implementation-plan', 'label': '实施计划', 'file_type': 'document', 'source_file': '03-实施计划/Snoopy Agent Smart (SAS) 实施计划.md'},
    {'id': 'build-record', 'label': '构建实录', 'file_type': 'document', 'source_file': '05-构建与验证/SAS-V1.5-构建实录.md'},
  ],
  'edges': [
    {'source': 'sc', 'target': 'sas', 'relation': 'references', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': 'README.md'},
    {'source': 'slow-is-fast', 'target': 'sas', 'relation': 'references', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': 'README.md'},
    {'source': 'ceo-mode', 'target': 'sas', 'relation': 'part_of', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': '04-工作准则/Snoopy Agent Smart (SAS)工作准则-v1.5.md'},
    {'source': 'ceo-mode', 'target': 'l0-user', 'relation': 'references', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': '04-工作准则/Snoopy Agent Smart (SAS)工作准则-v1.5.md'},
    {'source': 'ceo-mode', 'target': 'l1-sc', 'relation': 'references', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': '04-工作准则/Snoopy Agent Smart (SAS)工作准则-v1.5.md'},
    {'source': 'ceo-mode', 'target': 'l2-leader', 'relation': 'references', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': '04-工作准则/Snoopy Agent Smart (SAS)工作准则-v1.5.md'},
    {'source': 'ceo-mode', 'target': 'l3-worker', 'relation': 'references', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': '04-工作准则/Snoopy Agent Smart (SAS)工作准则-v1.5.md'},
    {'source': 'six-phase', 'target': 'sas', 'relation': 'part_of', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': 'README.md'},
    {'source': 'six-phase', 'target': 'phase-1', 'relation': 'part_of', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': 'README.md'},
    {'source': 'six-phase', 'target': 'phase-2', 'relation': 'part_of', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': 'README.md'},
    {'source': 'six-phase', 'target': 'phase-3', 'relation': 'part_of', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': 'README.md'},
    {'source': 'six-phase', 'target': 'phase-4', 'relation': 'part_of', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': 'README.md'},
    {'source': 'six-phase', 'target': 'phase-5', 'relation': 'part_of', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': 'README.md'},
    {'source': 'six-phase', 'target': 'phase-6', 'relation': 'part_of', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': 'README.md'},
    {'source': 'complexity-l1', 'target': 'auto-approval', 'relation': 'references', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': '04-工作准则/Snoopy Agent Smart (SAS)工作准则-v1.5.md'},
    {'source': 'complexity-l2', 'target': 'auto-approval', 'relation': 'references', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': '04-工作准则/Snoopy Agent Smart (SAS)工作准则-v1.5.md'},
    {'source': 'complexity-l3', 'target': 'auto-approval', 'relation': 'references', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': '04-工作准则/Snoopy Agent Smart (SAS)工作准则-v1.5.md'},
    {'source': 'phase-2', 'target': 'complexity-l1', 'relation': 'references', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': '04-工作准则/Snoopy Agent Smart (SAS)工作准则-v1.5.md'},
    {'source': 'phase-2', 'target': 'complexity-l2', 'relation': 'references', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': '04-工作准则/Snoopy Agent Smart (SAS)工作准则-v1.5.md'},
    {'source': 'phase-2', 'target': 'complexity-l3', 'relation': 'references', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': '04-工作准则/Snoopy Agent Smart (SAS)工作准则-v1.5.md'},
    {'source': 'l1-sc', 'target': 'permission-l1', 'relation': 'part_of', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': '04-工作准则/Snoopy Agent Smart (SAS)工作准则-v1.5.md'},
    {'source': 'l2-leader', 'target': 'permission-l2', 'relation': 'part_of', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': '04-工作准则/Snoopy Agent Smart (SAS)工作准则-v1.5.md'},
    {'source': 'l3-worker', 'target': 'permission-l3', 'relation': 'part_of', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': '04-工作准则/Snoopy Agent Smart (SAS)工作准则-v1.5.md'},
    {'source': 'l0-user', 'target': 'permission-l0', 'relation': 'part_of', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': '04-工作准则/Snoopy Agent Smart (SAS)工作准则-v1.5.md'},
    {'source': 'agent-main', 'target': 'l1-sc', 'relation': 'uses', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': 'README.md'},
    {'source': 'agent-main', 'target': 'model-m27-highspeed', 'relation': 'uses', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': '大模型信息与Agent分配依据.md'},
    {'source': 'agent-sas-leader', 'target': 'l2-leader', 'relation': 'uses', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': 'README.md'},
    {'source': 'agent-sas-leader', 'target': 'model-m27', 'relation': 'uses', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': '大模型信息与Agent分配依据.md'},
    {'source': 'agent-sas-default', 'target': 'model-m27-highspeed', 'relation': 'uses', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': '大模型信息与Agent分配依据.md'},
    {'source': 'agent-sas-sop-expert', 'target': 'model-m27', 'relation': 'uses', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': '大模型信息与Agent分配依据.md'},
    {'source': 'agent-sas-sop-expert', 'target': 'sop-expert-workflow', 'relation': 'uses', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': '04-工作准则/Snoopy Agent Smart (SAS)工作准则-v1.5.md'},
    {'source': 'agent-xiaowen', 'target': 'model-deepseek-chat', 'relation': 'uses', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': '大模型信息与Agent分配依据.md'},
    {'source': 'agent-hr', 'target': 'model-glm-5-turbo', 'relation': 'uses', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': '大模型信息与Agent分配依据.md'},
    {'source': 'agent-tech-news', 'target': 'model-glm-5-turbo', 'relation': 'uses', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': '大模型信息与Agent分配依据.md'},
    {'source': 'agent-doc-expert', 'target': 'model-glm-47', 'relation': 'uses', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': '大模型信息与Agent分配依据.md'},
    {'source': 'agent-weather', 'target': 'model-glm-45-air', 'relation': 'uses', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': '大模型信息与Agent分配依据.md'},
    {'source': 'model-m27-highspeed', 'target': 'provider-minimax', 'relation': 'part_of', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': '大模型信息与Agent分配依据.md'},
    {'source': 'model-m27', 'target': 'provider-minimax', 'relation': 'part_of', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': '大模型信息与Agent分配依据.md'},
    {'source': 'model-glm-5-turbo', 'target': 'provider-zhipu', 'relation': 'part_of', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': '大模型信息与Agent分配依据.md'},
    {'source': 'model-deepseek-chat', 'target': 'provider-deepseek', 'relation': 'part_of', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': '大模型信息与Agent分配依据.md'},
    {'source': 'tool-openclaw', 'target': 'sas', 'relation': 'uses', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': 'README.md'},
    {'source': 'tool-coze', 'target': 'sas', 'relation': 'uses', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': '04-工作准则/Snoopy Agent Smart (SAS)工作准则-v1.5.md'},
    {'source': 'tool-n8n', 'target': 'sas', 'relation': 'uses', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': '04-工作准则/Snoopy Agent Smart (SAS)工作准则-v1.5.md'},
    {'source': 'tool-github', 'target': 'sas', 'relation': 'uses', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': 'README.md'},
    {'source': 'tool-feishu', 'target': 'sas', 'relation': 'uses', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': '04-工作准则/Snoopy Agent Smart (SAS)工作准则-v1.5.md'},
    {'source': 'tool-task-decompose', 'target': 'phase-2', 'relation': 'uses', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': '05-构建与验证/SAS-V1.5-构建实录.md'},
    {'source': 'tool-task-logger', 'target': 'phase-3', 'relation': 'uses', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': '05-构建与验证/SAS-V1.5-构建实录.md'},
    {'source': 'tool-memory-lancedb', 'target': 'three-layer-arch', 'relation': 'part_of', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': '05-构建与验证/SAS-V1.5-构建实录.md'},
    {'source': 'tool-memory-lancedb', 'target': 'sc', 'relation': 'uses', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': '05-构建与验证/SAS-V1.5-构建实录.md'},
    {'source': 'tool-openclaw-lark', 'target': 'tool-feishu', 'relation': 'depends_on', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': '05-构建与验证/SAS-V1.5-构建实录.md'},
    {'source': 'harness-leader', 'target': 'tool-openclaw', 'relation': 'depends_on', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': '02-可行性分析/Snoopy Agent Smart (SAS) 可行性分析报告.md'},
    {'source': 'harness-leader', 'target': 'harness-framework', 'relation': 'references', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': '02-可行性分析/Snoopy Agent Smart (SAS) 可行性分析报告.md'},
    {'source': 'sas-v1-0', 'target': 'sas', 'relation': 'version_of', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': 'README.md'},
    {'source': 'sas-v1-1', 'target': 'sas-v1-0', 'relation': 'version_of', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': 'README.md'},
    {'source': 'sas-v1-2', 'target': 'sas-v1-1', 'relation': 'version_of', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': 'README.md'},
    {'source': 'sas-v1-3', 'target': 'sas-v1-2', 'relation': 'version_of', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': 'README.md'},
    {'source': 'sas-v1-4', 'target': 'sas-v1-3', 'relation': 'version_of', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': 'README.md'},
    {'source': 'sas-v1-5', 'target': 'sas-v1-4', 'relation': 'version_of', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': 'README.md'},
    {'source': 'sas-v1-6', 'target': 'sas-v1-5', 'relation': 'version_of', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': 'README.md'},
    {'source': 'sas-v1-5', 'target': 'ceo-mode', 'relation': 'part_of', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': '06-迭代记录/SAS-迭代记录-v1.5.0.md'},
    {'source': 'sas-v1-5', 'target': 'agent-capability-profile', 'relation': 'part_of', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': '06-迭代记录/SAS-迭代记录-v1.5.0.md'},
    {'source': 'sas-v1-5', 'target': 'task-report-card', 'relation': 'part_of', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': '06-迭代记录/SAS-迭代记录-v1.5.0.md'},
    {'source': 'sas-v1-5', 'target': 'complexity-l1', 'relation': 'part_of', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': '06-迭代记录/SAS-迭代记录-v1.5.0.md'},
    {'source': 'sas-v1-5', 'target': 'complexity-l2', 'relation': 'part_of', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': '06-迭代记录/SAS-迭代记录-v1.5.0.md'},
    {'source': 'sas-v1-5', 'target': 'complexity-l3', 'relation': 'part_of', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': '06-迭代记录/SAS-迭代记录-v1.5.0.md'},
    {'source': 'sas-v1-5', 'target': 'four-iron-rules', 'relation': 'part_of', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': '06-迭代记录/SAS-迭代记录-v1.5.0.md'},
    {'source': 'sas-v1-6', 'target': 'sas-efficiency', 'relation': 'part_of', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': '06-迭代记录/SAS-迭代记录-v1.6.0.md'},
    {'source': 'sas-v1-6', 'target': 'risk-prediction', 'relation': 'part_of', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': '06-迭代记录/SAS-迭代记录-v1.6.0.md'},
    {'source': 'sas-v1-6', 'target': 'user-feedback-loop', 'relation': 'part_of', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': '06-迭代记录/SAS-迭代记录-v1.6.0.md'},
    {'source': 'sas-v1-6', 'target': 'task-urgency', 'relation': 'part_of', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': '06-迭代记录/SAS-迭代记录-v1.6.0.md'},
    {'source': 'sas-v1-6', 'target': 'failure-archive', 'relation': 'part_of', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': '06-迭代记录/SAS-迭代记录-v1.6.0.md'},
    {'source': 'sas-v1-6', 'target': 'sas-v1-5', 'relation': 'version_of', 'confidence': 'EXTRACTED', 'confidence_score': 1.0, 'source_file': 'README.md'},
    {'source': 'sas-v1-5', 'target': 'l0-user', 'relation': 'part_of', 'confidence': 'EXTRACTED', '